Write env.py to generate apt and snap lists
This Python script is mostly just a translation of some shell scripts
that I was able to find online, linked below.

PPAs
----

For `apt` PPAs, [this Ask Ubuntu answer][askubuntu ppa] gives a shell
script:

> With a little cleanup I got a script that lists the PPAs, but not any
> other repository:
>
> ```sh
> #! /bin/sh
> # listppa Script to get all the PPA installed on a system ready to share for reininstall
> for APT in `find /etc/apt/ -name \*.list`; do
>     grep -o "^deb http://ppa.launchpad.net/[a-z0-9\-]\+/[a-z0-9\-]\+" $APT | while read ENTRY ; do
>         USER=`echo $ENTRY | cut -d/ -f4`
>         PPA=`echo $ENTRY | cut -d/ -f5`
>         echo sudo apt-add-repository ppa:$USER/$PPA
>     done
> done
> ```
>
> When you call it with `listppa > installppa.sh` you get a script you
> can copy on a new machine to reinstall all PPA.

I removed the `sudo apt-add-repository ppa:` bit and sorted the results
since I'm going to be keeping this list in version control.

Packages
--------

For `apt` packages, [this Ask Ubuntu answer][askubuntu package] gives
two (apparently equivalent) Bash one-liners:

> **Using `apt-mark`:**
>
> ```bash
> comm -23 <(apt-mark showmanual | sort -u) <(gzip -dc /var/log/installer/initial-status.gz | sed -n 's/^Package: //p' | sort -u)
> ```
>
> **Using `aptitude`:**
>
> ```bash
> comm -23 <(aptitude search '~i !~M' -F '%p' | sed "s/ *$//" | sort -u) <(gzip -dc /var/log/installer/initial-status.gz | sed -n 's/^Package: //p' | sort -u)
> ```

They do indeed give the same output on my machine.

> **How does it work:**
>
> 1. Get the list of manually installed packages. For aptitude, the
>    additional `sed` strips out remaining whitespace at the end of the
>    line.
> 2. Get the list of packages installed right after a fresh install.
> 3. Compare the files, only output the lines in file 1 that are not
>    present in file 2.

I took the shorter version because judging by my current `env.sh`, it
looks like `aptitude` doesn't come pre-installed in Ubuntu.

Snaps
-----

There's [an Ask Ubuntu question][askubuntu snap] that asks how to list
manually installed snaps (the asker seems to be doing something similar
to what I'm doing in this repository) but it has no answers.

I thought about not including the channel for each snap since the only
ones using something besides `latest/stable` were `node` and
`shellcheck`, but then I tried to reinstall `node` without specifying a
channel and it didn't work:

> ```
> error: snap "node" is not available on stable but is available to install on the following
>        channels:
>
>        edge       snap install --edge node
>
>        Please be mindful pre-release channels may include features not completely tested or
>        implemented. Get more information with 'snap info node'.
> ```

[askubuntu ppa]: https://askubuntu.com/a/148968/423065
[askubuntu package]: https://askubuntu.com/a/492343/423065
[askubuntu snap]: https://askubuntu.com/q/1152682/423065
[shellcheck]: https://github.com/koalaman/shellcheck/tree/v0.7.1#installing